name: Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_branch:
        type: string
        default: gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: echo  "${{ vars.BUILD_DOTENV }}" > .env
      - run: npm i
      - run: npm run build
      - run: npm run
      - run: |
          git switch -f --orphan ${{ inputs.build_branch }} \
          && git reset \
          && git add -f build \
          && git config user.email 'actions@github.com' \
          && git commit -m 'build' \
          && git push -f -u origin ${{ inputs.build_branch }}
    

